# Generated by Django 3.0.1 on 2019-12-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_balancer', '0002_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.IntegerField(choices=[(0, 'Stock'), (1, 'Fii'), (2, 'Reit'), (3, 'Etf'), (4, 'Crypto')], default=0),
            preserve_default=False,
        ),
    ]
