# Generated by Django 3.0.1 on 2019-12-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_balancer', '0005_auto_20191227_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price_currency',
            new_name='unit_price_currency',
        ),
    ]
