# Generated by Django 3.0.1 on 2019-12-27 20:01

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('assets_balancer', '0008_auto_20191227_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='BRL', max_digits=14, null=True, validators=[djmoney.models.validators.MinMoneyValidator({'BRL': 0})]),
        ),
    ]
